discovery:
  nodes: "127.0.0.1:7171"

whitelist:
  list:
    - 123
  log: /tmp/white_list.log

protocol:
  timer: 32
  timerSize: 2048
  cliProto: 5
  svrProto: 10
  handshakeTimeout: 8

websocket:
  bind:
    - :3102
  tlsOpen: false
  tlsBind:
    - :3103
  certFile: ../../cert.pem
  privateFile: ../../private.pem

tcp:
  bind:
    - :3101
  sndbuf: 4096
  rcvbuf: 4096
  keepalive: false
  reader: 32
  readBuf: 1024
  readBufSize: 8192
  writer: 32
  writeBuf: 1024
  writeBufSize: 8192

rpc_client:
  dial: 1
  timeout: 1

rpc_server:
  addr: ":3109"
  timeout: 1

bucket:
  size: 32
  channel: 1024
  room: 1024
  routineAmount: 32
  routineSize: 1024
